[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  m5stack/M5Unified @ ^0.2.2
  m5stack/M5CoreS3 @ ^1.0.1
  bblanchon/ArduinoJson @ ^7.0.0
  fastled/FastLED @ ^3.9.0
  espressif/esp32-camera @ ^2.0.0
  alvarowolfx/ESP32QRCodeReader @ ^1.1.0
  knolleary/PubSubClient @ ^2.8

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM

; Para upload via OTA (item #21), descomente e ajuste:
; upload_protocol = espota
; upload_port = cubinho.local
