[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  m5stack/M5Unified @ ^0.2.2
  bblanchon/ArduinoJson @ ^7.0.0
  fastled/FastLED @ ^3.9.0

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
